In [ ]:
import numpy as np

**(1)** Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [ ]:
squaremeter = [150, 300, 250, 500, 120, 280, 200, 170, 380, 430]
rooms = [2, 3, 3, 5, 1, 3, 2, 1, 3, 4]
price = [600000, 1000000, 750000, 3000000, 300000, 400000, 450000, 170000, 630000, 890000]

houses = np.array([squaremeter, rooms, price])
houses

array([[    150,     300,     250,     500,     120,     280,     200,
            170,     380,     430],
       [      2,       3,       3,       5,       1,       3,       2,
              1,       3,       4],
       [ 600000, 1000000,  750000, 3000000,  300000,  400000,  450000,
         170000,  630000,  890000]])

**(2)** Transpose the array you have created, so that every line can represent features of one house.

In [ ]:
houses_transposed = houses.transpose()
houses_transposed

array([[    150,       2,  600000],
       [    300,       3, 1000000],
       [    250,       3,  750000],
       [    500,       5, 3000000],
       [    120,       1,  300000],
       [    280,       3,  400000],
       [    200,       2,  450000],
       [    170,       1,  170000],
       [    380,       3,  630000],
       [    430,       4,  890000]])

**(3)** Display the shape of the array and explain what it means.

In [ ]:
houses.shape
# houses array contain 3 rows and 10 columns

(3, 10)

**(4)** Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [ ]:
arr = np.ones((6, 5))
arr[1:6:2, 1:6:2] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.]])